SELECT 
	tblChkCon.CONSTRAINT_CATALOG,
	tblChkCon.CONSTRAINT_SCHEMA,
	tblChkCon.CONSTRAINT_NAME,
	tblChkCon.CHECK_CLAUSE
FROM
	INFORMATION_SCHEMA.CHECK_CONSTRAINTS AS tblChkCon
WHERE
	tblChkCon.CONSTRAINT_NAME = '@ConstraintName'