SELECT
	tblCol.TABLE_CATALOG,
	tblCol.TABLE_SCHEMA,
	tblCol.TABLE_NAME,
	tblCol.COLUMN_NAME,
	tblCol.ORDINAL_POSITION,
	tblCol.COLUMN_DEFAULT,
	tblCol.IS_NULLABLE,
	tblCol.DATA_TYPE,
	tblCol.CHARACTER_MAXIMUM_LENGTH,
	tblCol.CHARACTER_OCTET_LENGTH,
	tblCol.NUMERIC_PRECISION,
	tblCol.NUMERIC_PRECISION_RADIX,
	tblCol.NUMERIC_SCALE
FROM 
	INFORMATION_SCHEMA.COLUMNS AS tblCol
WHERE
	tblCol.TABLE_NAME = '@TableName'