SELECT
	tblRoutine.SPECIFIC_CATALOG,
	tblRoutine.SPECIFIC_SCHEMA,
	tblRoutine.SPECIFIC_NAME,
	tblRoutine.ROUTINE_CATALOG,
	tblRoutine.ROUTINE_SCHEMA,
	tblRoutine.ROUTINE_NAME,
	tblRoutine.ROUTINE_TYPE,
	tblRoutine.DATA_TYPE,
	tblRoutine.CHARACTER_MAXIMUM_LENGTH,
	tblRoutine.CHARACTER_OCTET_LENGTH,
	tblRoutine.NUMERIC_PRECISION,
	tblRoutine.NUMERIC_PRECISION_RADIX,
	tblRoutine.NUMERIC_SCALE,
	tblRoutine.ROUTINE_BODY,
	tblRoutine.ROUTINE_DEFINITION,
	tblRoutine.IS_DETERMINISTIC,
	tblRoutine.IS_IMPLICITLY_INVOCABLE,
	tblRoutine.CREATED,
	tblRoutine.LAST_ALTERED
FROM
	INFORMATION_SCHEMA.ROUTINES AS tblRoutine
WHERE
	tblRoutine.ROUTINE_NAME = '@RoutineName'
	
	
SELECT
	tblRoutineParam.SPECIFIC_CATALOG,
	tblRoutineParam.SPECIFIC_SCHEMA,
	tblRoutineParam.SPECIFIC_NAME,
	tblRoutineParam.ORDINAL_POSITION,
	tblRoutineParam.PARAMETER_MODE,
	tblRoutineParam.IS_RESULT,
	tblRoutineParam.AS_LOCATOR,
	tblRoutineParam.PARAMETER_NAME,
	tblRoutineParam.DATA_TYPE,
	tblRoutineParam.CHARACTER_MAXIMUM_LENGTH,
	tblRoutineParam.CHARACTER_OCTET_LENGTH,
	tblRoutineParam.NUMERIC_PRECISION,
	tblRoutineParam.NUMERIC_PRECISION_RADIX,
	tblRoutineParam.NUMERIC_SCALE
FROM
	INFORMATION_SCHEMA.PARAMETERS AS tblRoutineParam
WHERE
	tblRoutineParam.SPECIFIC_NAME = '@RoutineName'
	
	
SELECT
	tblRoutineCol.TABLE_CATALOG,
	tblRoutineCol.TABLE_SCHEMA,
	tblRoutineCol.TABLE_NAME,
	tblRoutineCol.COLUMN_NAME,
	tblRoutineCol.ORDINAL_POSITION,
	tblRoutineCol.COLUMN_DEFAULT,
	tblRoutineCol.IS_NULLABLE,
	tblRoutineCol.DATA_TYPE,
	tblRoutineCol.CHARACTER_MAXIMUM_LENGTH,
	tblRoutineCol.CHARACTER_OCTET_LENGTH,
	tblRoutineCol.NUMERIC_PRECISION,
	tblRoutineCol.NUMERIC_PRECISION_RADIX,
	tblRoutineCol.NUMERIC_SCALE
FROM 
	INFORMATION_SCHEMA.ROUTINE_COLUMNS AS tblRoutineCol
WHERE
	tblRoutineCol.TABLE_NAME = '@RoutineName'