SELECT
	tblRoutine.SPECIFIC_CATALOG,
	tblRoutine.SPECIFIC_SCHEMA,
	tblRoutine.SPECIFIC_NAME,
	tblRoutine.ROUTINE_CATALOG,
	tblRoutine.ROUTINE_SCHEMA,
	tblRoutine.ROUTINE_NAME,
	tblRoutine.ROUTINE_TYPE,
	tblRoutine.DATA_TYPE,
	tblRoutine.CHARACTER_MAXIMUM_LENGTH,
	tblRoutine.CHARACTER_OCTET_LENGTH,
	tblRoutine.NUMERIC_PRECISION,
	tblRoutine.NUMERIC_PRECISION_RADIX,
	tblRoutine.NUMERIC_SCALE,
	tblRoutine.ROUTINE_BODY,
	tblRoutine.ROUTINE_DEFINITION,
	tblRoutine.IS_DETERMINISTIC,
	tblRoutine.IS_IMPLICITLY_INVOCABLE,
	tblRoutine.CREATED,
	tblRoutine.LAST_ALTERED
FROM
	INFORMATION_SCHEMA.ROUTINES AS tblRoutine
WHERE
	tblRoutine.ROUTINE_NAME = '@RoutineName'